# Generated by Django 4.2.1 on 2023-06-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='drive.folder'),
        ),
    ]
