# Generated by Django 4.2.1 on 2023-06-19 18:59

from django.db import migrations, models

import drive.models


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0002_alter_files_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/files',
                                   validators=[drive.models.validate_file_size]),
        ),
    ]
