# Generated by Django 4.2.1 on 2023-06-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0003_remove_userpreference_name_userpreference_theme_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='theme_mode',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='name',
            field=models.CharField(default='dark', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='view_mode',
            field=models.BooleanField(default=False),
        ),
    ]
