# Generated by Django 4.2.1 on 2023-06-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0004_remove_userpreference_theme_mode_userpreference_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='name',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='theme_mode',
            field=models.CharField(default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='view_mode',
            field=models.CharField(default='table', max_length=10),
        ),
    ]
