# Generated by Django 4.2.1 on 2023-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drive', '0005_remove_userpreference_name_userpreference_theme_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme_mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='view_mode',
            field=models.CharField(max_length=10),
        ),
    ]
